title: Liminal Horror
permalink: pretty
remote_theme: pmarsceill/just-the-docs
baseurl: "/LiminalHorror"
url: ""
logo: "/img/logo1.png"
aux_links:
  "Liminal Horror su GitHub":
    - "//github.com/Italian-Translation-Alliance/LiminalHorror"
  "PDF":
    - "//ita-translation-alliance.itch.io/liminal-horror"
  "Lulu":
    - "//www.lulu.com/en/en/shop/nick-erickson-and-roberto-bisceglie/liminal-horror-versione-italiana/paperback/product-n5npm4.html?page=1&pageSize=4"
  "Amazon":  
    "//www.amazon.it/dp/B09HFXXJMC"
color_scheme: light
plugins:
  - jekyll-redirect-from
include:
    -js

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Liminal Horror è stato scritto e progettato da Goblin Archives"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-198234886-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)
